### ISSUE TITLE
No shilman-react-components

### ISSUE THREAD

**Issue by fortunto2** [shilman/nova-spike#2]
Hi, when npm install

404 Registry returned 404 for GET on https://registry.npmjs.org/shilman-react-components

**Comment by shilman** [comment]
I'm not seeing that problem. Which file references `shilman-react-components`?

**Comment by fortunto2** [comment]
`rustam@rustam-SSD:~/lifefilm/nova-spike/nova-base-components$ sudo npm install
[sudo] пароль для rustam: 
npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/shilman-react-components
npm ERR! 404 
npm ERR! 404  'shilman-react-components' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'nova-base-components'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

`
